package com.github.yuweiguocn.demo.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.github.yuweiguocn.demo.greendao.db.TestData;

import com.github.yuweiguocn.demo.greendao.db.TestDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDataDaoConfig;
    private final TestDataDao testDataDao;

    public DaoSession(Database db,
                      IdentityScopeType type,
                      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        testDataDaoConfig = daoConfigMap.get(TestDataDao.class).clone();
        testDataDaoConfig.initIdentityScope(type);

        testDataDao = new TestDataDao(testDataDaoConfig, this);
        registerDao(TestData.class, testDataDao);
    }
    
    public void clear() {
        testDataDaoConfig.clearIdentityScope();
    }

    public TestDataDao getTestDataDao() {
        return testDataDao;
    }
}
